// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f418e9e8-06fa-4571-905d-53ff17e64ce7",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_5VO3kupyo",
    "aws_user_pools_web_client_id": "1o9r83bmmhmi00pce62h4l7il2",
    "aws_user_files_s3_bucket": "pwahomefoodbfb350b25bb0440080dffa6fddf05a59",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://7ofl2vitt5eetaheo2o7y2bxxa.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
